// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ExitData {
  bytes32 targetRoomId;
  string direction;
}

library Exit {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "Exit", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000045786974000000000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0020010120000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32, string)
  Schema constant _valueSchema = Schema.wrap(0x002001015fc50000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "roomId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "targetRoomId";
    fieldNames[1] = "direction";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get targetRoomId.
   */
  function getTargetRoomId(bytes32 roomId) internal view returns (bytes32 targetRoomId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get targetRoomId.
   */
  function _getTargetRoomId(bytes32 roomId) internal view returns (bytes32 targetRoomId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set targetRoomId.
   */
  function setTargetRoomId(bytes32 roomId, bytes32 targetRoomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((targetRoomId)), _fieldLayout);
  }

  /**
   * @notice Set targetRoomId.
   */
  function _setTargetRoomId(bytes32 roomId, bytes32 targetRoomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((targetRoomId)), _fieldLayout);
  }

  /**
   * @notice Get direction.
   */
  function getDirection(bytes32 roomId) internal view returns (string memory direction) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get direction.
   */
  function _getDirection(bytes32 roomId) internal view returns (string memory direction) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set direction.
   */
  function setDirection(bytes32 roomId, string memory direction) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((direction)));
  }

  /**
   * @notice Set direction.
   */
  function _setDirection(bytes32 roomId, string memory direction) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((direction)));
  }

  /**
   * @notice Get the length of direction.
   */
  function lengthDirection(bytes32 roomId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of direction.
   */
  function _lengthDirection(bytes32 roomId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of direction.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemDirection(bytes32 roomId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of direction.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemDirection(bytes32 roomId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to direction.
   */
  function pushDirection(bytes32 roomId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to direction.
   */
  function _pushDirection(bytes32 roomId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from direction.
   */
  function popDirection(bytes32 roomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from direction.
   */
  function _popDirection(bytes32 roomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of direction at `_index`.
   */
  function updateDirection(bytes32 roomId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of direction at `_index`.
   */
  function _updateDirection(bytes32 roomId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 roomId) internal view returns (ExitData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 roomId) internal view returns (ExitData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 roomId, bytes32 targetRoomId, string memory direction) internal {
    bytes memory _staticData = encodeStatic(targetRoomId);

    EncodedLengths _encodedLengths = encodeLengths(direction);
    bytes memory _dynamicData = encodeDynamic(direction);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 roomId, bytes32 targetRoomId, string memory direction) internal {
    bytes memory _staticData = encodeStatic(targetRoomId);

    EncodedLengths _encodedLengths = encodeLengths(direction);
    bytes memory _dynamicData = encodeDynamic(direction);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 roomId, ExitData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.targetRoomId);

    EncodedLengths _encodedLengths = encodeLengths(_table.direction);
    bytes memory _dynamicData = encodeDynamic(_table.direction);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 roomId, ExitData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.targetRoomId);

    EncodedLengths _encodedLengths = encodeLengths(_table.direction);
    bytes memory _dynamicData = encodeDynamic(_table.direction);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (bytes32 targetRoomId) {
    targetRoomId = (Bytes.getBytes32(_blob, 0));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory direction) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    direction = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (ExitData memory _table) {
    (_table.targetRoomId) = decodeStatic(_staticData);

    (_table.direction) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 roomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 roomId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bytes32 targetRoomId) internal pure returns (bytes memory) {
    return abi.encodePacked(targetRoomId);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory direction) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(direction).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory direction) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((direction)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32 targetRoomId,
    string memory direction
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(targetRoomId);

    EncodedLengths _encodedLengths = encodeLengths(direction);
    bytes memory _dynamicData = encodeDynamic(direction);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 roomId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = roomId;

    return _keyTuple;
  }
}
