// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library QuestStatus {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "QuestStatus", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000051756573745374617475730000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0001010001000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, address)
  Schema constant _keySchema = Schema.wrap(0x003402005f610000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8)
  Schema constant _valueSchema = Schema.wrap(0x0001010000000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "questId";
    keyNames[1] = "participant";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "status";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get status.
   */
  function getStatus(bytes32 questId, address participant) internal view returns (uint8 status) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get status.
   */
  function _getStatus(bytes32 questId, address participant) internal view returns (uint8 status) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get status.
   */
  function get(bytes32 questId, address participant) internal view returns (uint8 status) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get status.
   */
  function _get(bytes32 questId, address participant) internal view returns (uint8 status) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set status.
   */
  function setStatus(bytes32 questId, address participant, uint8 status) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((status)), _fieldLayout);
  }

  /**
   * @notice Set status.
   */
  function _setStatus(bytes32 questId, address participant, uint8 status) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((status)), _fieldLayout);
  }

  /**
   * @notice Set status.
   */
  function set(bytes32 questId, address participant, uint8 status) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((status)), _fieldLayout);
  }

  /**
   * @notice Set status.
   */
  function _set(bytes32 questId, address participant, uint8 status) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((status)), _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 questId, address participant) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 questId, address participant) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint8 status) internal pure returns (bytes memory) {
    return abi.encodePacked(status);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(uint8 status) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(status);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 questId, address participant) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = questId;
    _keyTuple[1] = bytes32(uint256(uint160(participant)));

    return _keyTuple;
  }
}
