// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TradeRequest, TradeRequestData } from "./tables/TradeRequest.sol";
import { TradeOffer, TradeOfferData } from "./tables/TradeOffer.sol";
import { Quest, QuestData } from "./tables/Quest.sol";
import { QuestStatus } from "./tables/QuestStatus.sol";
import { Player, PlayerData } from "./tables/Player.sol";
import { Lore, LoreData } from "./tables/Lore.sol";
import { Inventory } from "./tables/Inventory.sol";
import { Item, ItemData } from "./tables/Item.sol";
