// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IDynamicQuestSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDynamicQuestSystem {
  function createQuest(string memory questName, string memory questDescription, uint8 rewardItemId) external;

  function completeQuest(bytes32 questId) external;
}
