// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PlayerData } from "./../index.sol";

/**
 * @title ISpawnPlayerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISpawnPlayerSystem {
  function spawnPlayer(bytes32 id, PlayerData calldata data) external;
}
